### ISSUE TITLE
sensor.reset() crashes if you shut down the OV7725 regulator

### ISSUE THREAD

**Issue by acutetech** [openmv/openmv#883]
I prepared a fairly simple script to investigate power saving tactics. If I attempt to save power by shutting down the OV7725 regulator with this:

    sensor.__write_reg(0x4F, 0x18)

then I get this error when next calling sensor.reset():
    "OSError: Reset Failed"

I prepared a script "simple_sleep.py" available in a forum post "Low duty cycle to save power: examples?" which should allow the problem to be replicated: https://forums.openmv.io/viewtopic.php?f=6&t=1997&sid=519d03826cb81f2bcb02a622cfb9e1e0 The script is copiously documented.

One of three power-saving options can be chosen at around line 152, by uncommenting one of the three options. The option pause("none", False) works OK but pause("none", True) will cause the crash. ("True" means "shut down OV7725 regulator).

The problem occurs with both H7 and M7 cameras. Firmware is 3.6.7. Problem is revealed when running code from the IDE.

**Comment by iabdalkader** [comment]
Oh I see you copied that from our example, this is wrong I fixed it and moved soft sleep before shutting down the regulator. I noticed that I get less power consumption with both sensor.sleep and the shutting down the regulator, can you confirm this ?

**Comment by acutetech** [comment]
I am happy to repeat whatever you find, but you imply there are issues your own example (which I copied). Perhaps you can send me a revised example for me to test. My example (and yours) calls 4 routines as an attempt to reduce sensor power consumption, which gives 16 combinations, even before one looks at changing the sequence:
    sensor.reset()
    sensor.__write_reg(0x4F, 0x18)
    sensor.sleep(True)
    sensor.shutdown(True)

I am happy to look at the underlying C code for these, and compare against the data sheets (camera and processor), if you can point me at the code.

**Comment by kwagyeman** [comment]
Reset https://github.com/openmv/openmv/blob/master/src/omv/ov7725.c#L152
Sleep https://github.com/openmv/openmv/blob/master/src/omv/ov7725.c#L171
Shutdown https://github.com/openmv/openmv/blob/master/src/omv/sensor.c#L529

Note that the STM32s I/O pins float when you turn it off. This prevents shutdown from working as the pin causing the shutdown looses drive and floats which causes the camera to wake up. Yes, this is a design issue.

**Comment by iabdalkader** [comment]
Like I mentioned before, here and in the other issue, you just need to move sleep before shutting down the sensor's regulator and it should work fine. I already fixed this in the example. I noticed the lowest power consumption with the following sequence:
```
sensor.reset()

# Enable sensor softsleep
sensor.sleep(True)

# Optionally bypass the regulator on OV7725
# for the lowest possible power consumption.
if (sensor.get_id() == sensor.OV7725):
    # Bypass internal regulator
    sensor.__write_reg(0x4F, 0x18)

# Shutdown the sensor (pulls PWDN high).
sensor.shutdown(True)

# Enable RTC interrupts every 30 seconds.
# Note the camera will RESET after wakeup from Deepsleep Mode.
rtc.wakeup(10000)

# Enter Deepsleep Mode.
machine.deepsleep()
```

**Comment by acutetech** [comment]
Regarding floating pins in Standby state: the RM0433 Reference Manual says: "In Standby mode, all I/O pins are high impedance without pull, except for... WKUP pins (if enabled)."  This is unfortunate behaviour: other processors leave GPIO pins unchanged when sleeping. 
Up to 6 pins have WKUP functionality (only 4 on the STM32H743 LQFP100 package) and can be programmed with pull-up or pull-down resistors. The DCMI_PWDN pin is not one of them, unfortunately, so an external pull-up would be required to prevent this pin floating. Not easy to add to the existing hardware...
However, this is likely to be a more general issue, as floating input pins on chips are generally a bad thing and often lead to excessive current drawn as the pin floats through a non-logic voltage, or to unwanted behaviour as the pin floats to an unwanted logic level. It could possibly cause problems with other camera pins (the reset pin, for instance). 
Users should be warned to attend to this with any external circuitry they add. In general, resistors should be the highest practical value so that unneccessary current does not flow through them when the pin is driven to the opposite logic state. (330uA can be wasted through every 10k resistor with 3.3V across it).

**Comment by acutetech** [comment]
The OV7725 data sheet gives a sleep current of 1mA with a software-initiated standby and 20uA with a PWDN pin initiated standby. My reading of this is that these are alternatives, with the PWDN being best. However, as noted, the pin used by the OpenMV floats when the processor enters standby. 
Furthermore, the OV7725 data sheet refers to an internal pull-down resistor on PWDN (value not stated), so as soon as the processor enters its Standby its GPIO pin will float and the OV7725 pull-down will take the OV7725 out of its standby. Unfortunately I can't check this with an oscilloscope at present.
So my best attempt at an analysis is that (a) sensor.shutdown(True) is futile without adding a pull-up resistor; (b) sensor.sleep(True) (invoking soft sleep mode) is the best that can be done, but will only reduce OV7725 current to 1mA; (c) but a floating OV7725 RSTB pin is likely to reset the camera chip, returning the COM2 register to its default state, which is with soft sleep mode disabled. So this is probably futile as well....
My best analysis without a scope and fine-pitch soldering setup is that new PCB design of the camera module is required, with high-value pull-up resistors on SHDN, RSTB and FSIN

**Comment by kwagyeman** [comment]
Yeah, it needs to be fixed. On new designs we have been good about adding stuff like this. We have a new Group Gets board in the works for Thermal + Regular vision which implements all low power features correctly along with RTC support, a battery, and etc.

From this design for new boards we make we will raise the quality.

**Comment by acutetech** [comment]
Hi guys - I tested your recommended change (which was to move sensor.sleep() from after sensor.__write_reg(0x4F, 0x18) to before it). Results, including power consumption, are unchanged with one exception: the rare crashes in the standby test (pyb.standby()) no longer happen. Why this is I cannot understand. 

However, I still see the problem when resuming from pyb.stop(), which means the regulator cannot be shut off when using pyb.stop(). And I still get the crash when executing sensor.reset() after shutting off the regulator (not a plausible use case by itself, but a pointer to where the problem lies with the other examples).

The issues raised in earlier posts (and in comments in simple_sleep.py) remain: floating SHDN pin, 330uA current wasted through the 10k pull-up R9 on the MOSFET Q2. The best sleep current I have measured is c. 500uA in Standby state (of which 330uA is through R9 and probaby 40uA in the PAM2305 regulator).

IMHO you should extend your own IDE low-power examples which only shut the processor down and do not resume again - these are therefore not realistic use cases: users will want to resume. If you do this then the issues discussed here will be plain, and you will be able to suggest to users the best achievable outcomes.

**Comment by iabdalkader** [comment]
Hi @acutetech you must have missed my comment on your other issue, here I'll put it here again:

> If you shut down the regulator there's no way to turn it back on without resetting the whole camera. Note sensor.reset() does Not toggle the reset GPIO, maybe it should, instead it performs a soft-reset and re-writes the default registers, so it needs I2C working (the regulator on). Since standby resets the camera anyway, you should be able to shut-down the regulator, followed by standby just don't call any other sensor functions after shutting down the regulator.

Also let me add this, it's not a very important distinction but the cam doesn't actually "crash" it should raise an exception when I2C fails or times out, or maybe get stuck somewhere, I don't think this results in an actual crash.

> And I still get the crash when executing sensor.reset() after shutting off the regulator

I hope my comment above explains why this happens. Now I may have an actual fix for this, I'll make sensor.reset() toggle the reset GPIO (do a hard-reset) which should turn the regulator back on. This will add a few milliseconds delay to every sensor reset, I guess it's acceptable @kwagyeman

**Comment by kwagyeman** [comment]
Cool

**Comment by acutetech** [comment]
Hi guys - I guess I missed the significance of "resetting the whole camera." - perhaps I thought "camera" meant "sensor".
But toggling the OV7725 reset pin at the start of sensor.reset(), and taking the SHDN pin inactive, is definately the right thing to do IMHO. "Reset" should mean "restore to a known state regardless of whatever the old state was".  From what you say it should fix two of the three the problems I see. 
For the third, I speculate that when the processor enters standby state the reset pin _usually_ floats to the reset level (0) and so returns the registers to their default state and the regulator is re-enabled. If in some cases perhaps the reset pin does not float low then maybe this does not happen and my setup hangs up?
These pins seem to be manipulated in  sensor_init() code here: https://github.com/openmv/openmv/blob/master/src/omv/sensor.c#L250 but I don't see where this is called...
Finally, IMHO it would be useful adding to the documentation of sensor.reset(), sensor.sleep(), sensor.shutdown() to explain what is happening at the hardware and register level.

**Comment by acutetech** [comment]
You are right when you say "the cam doesn't actually "crash" it should raise an exception" - when I add try/except code around the sensor reset I get an error message 'Reset Failed'. But this is unrecoverable at present, so to all intents and purposes the system is dead.

**Comment by iabdalkader** [comment]
Hello, sensor.reset() will now do a hard-reset as discussed, this allows recovering after a regulator shut-down, and in the next hardware revision we'll fix the other issues.
